all: a_Declared_solution.html b_Added_value.html c_Weighting.html

a_Declared_solution.html:

b_Added_value.html:

c_Weighting.html:

clean:
	$(RM) a_Declared_solution.tex b_Added_value.tex c_Weighting.tex
